--------------------------------------------------------------------------
--script for auto_funcs.h and auto_funcs.cpp generation
--expects LuaJIT
--------------------------------------------------------------------------

--load parser module
package.path = package.path..";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local save_data = cpp2ffi.save_data
local copyfile = cpp2ffi.copyfile
--take script args---------------------------
local COMPILER, CPRE, INTERNAL_GENERATION, COMMENTS_GENERATION = cpp2ffi.GetScriptArgs({[[IMPLOT_DISABLE_OBSOLETE_FUNCTIONS]]},...)
--------------------------------------------------------------------------
--this table has the functions to be skipped in generation
--------------------------------------------------------------------------
local cimgui_manuals = {
     --ImPlot_PlotLineG = true,
}
local cimgui_skipped = {
	 --ImPlot_AnnotateClamped = true
}
--------------------------------------------------------------------------
--this table is a dictionary to force a naming of function overloading (instead of algorythmic generated)
--first level is cimguiname without postfix, second level is the signature of the function, value is the
--desired name
---------------------------------------------------------------------------
local cimgui_overloads = {
    --igPushID = {
        --["(const char*)"] =           "igPushIDStr",
        --["(const char*,const char*)"] = "igPushIDRange",
        --["(const void*)"] =           "igPushIDPtr",
        --["(int)"] =                   "igPushIDInt"
    --},
}

--------------------------header definitions
local cimgui_header = 
[[//This file is automatically generated by generator.lua from https://github.com/cimgui/cimplot
//based on implot.h file version XXX from implot https://github.com/epezent/implot
]]

if INTERNAL_GENERATION then
	cimgui_header = cimgui_header..[[//with implot_internal.h api
]]
end
--------------------------------------------------------------------------
--helper functions
--------------------------------functions for C generation
--load parser module
package.path = package.path .. ";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local save_data = cpp2ffi.save_data
local copyfile = cpp2ffi.copyfile

--------------------------------------------------------
-----------------------------do it----------------------
--------------------------------------------------------
--get implot.h version--------------------------
local pipe,err = io.open("../implot/implot.h","r")
if not pipe then
    error("could not open file:"..err)
end
local implot_version
while true do
    local line = pipe:read"*l"
    implot_version = line:match([[ImPlot%s+v(.+)]])
    if implot_version then break end
end
pipe:close()
cimgui_header = cimgui_header:gsub("XXX",implot_version)
print("IMPLOT_VERSION",implot_version)

----------------------------------custom generators for implot_PlotXXXXG
--functions having ImPlotGetter

local function custom_header(outtab, def)
	if not def.args:match"ImPlotGetter " then return false end
	local args = def.args:gsub("ImPlotGetter","ImPlotPoint_getter")
	table.insert(outtab,"CIMGUI_API "..def.ret.." ".. def.ov_cimguiname.."_LJ" ..args..";//custom generation\n")
	return false --true
end
local function custom_implementation(outtab,def, FP)
	if not def.args:match"ImPlotGetter " then return false end
	local def2 = cpp2ffi.deepcopy(def)
	def2.args = def2.args:gsub("ImPlotGetter","ImPlotPoint_getter")
	def2.signature = def2.signature:gsub("ImPlotGetter","ImPlotPoint_getter")
	def2.ov_cimguiname = def2.ov_cimguiname .. "_LJ"
	--cpp2ffi.prtable(def2)
    table.insert(outtab,"CIMGUI_API".." "..def2.ret.." "..def2.ov_cimguiname..def2.args.."//custom implementation\n")
	--cpp2ffi.prtable(def)
    table.insert(outtab,"{\n")
	local ngetter = 0
	---[[
	local call_args = def.call_args
	for i,arg in ipairs(def.argsT) do
		if arg.type == "ImPlotGetter" then
			ngetter = ngetter + 1
			table.insert(outtab,"    getter_funcX"..((ngetter==1 and "") or (ngetter==2 and "2") or error"too much getters").." = "..arg.name..";\n")
			call_args = call_args:gsub(arg.name, ((ngetter==1 and "Wrapper") or (ngetter==2 and "Wrapper2")))
			def2.argsT[i].type = "ImPlotPoint_getter"
		end
	end
	def2.call_args = call_args
	--]]
	--[[
	local call_args = "("
	for i,arg in ipairs(def.argsT) do
		if arg.type == "ImPlotGetter" then
			arg.custom_type = "ImPlotPoint_getter"
			ngetter = ngetter + 1
			table.insert(outtab,"    getter_funcX"..((ngetter==1 and "") or (ngetter==2 and "2") or error"too much getters").." = "..arg.name..";\n")
			call_args = call_args..((ngetter==1 and "Wrapper,") or (ngetter==2 and "Wrapper2,"))
		else
			call_args = call_args..arg.name..","
		end
	end
	call_args = call_args:sub(1,-2)..")"
	print("call_args",call_args)
	--]]
	table.insert(outtab,"    ImPlot::"..def2.funcname..call_args..";\n")
    table.insert(outtab,"}\n")
	FP.defsT[def2.cimguiname.."_LJ"]  = {def2}
	return false --true
end
-------------funtion for parsing implot headers
local function parseImGuiHeader(header,names,modulename)
	--prepare parser
	local parser = cpp2ffi.Parser()
	parser.modulename = modulename
	parser.getCname = function(stname,funcname,namespace)
		local pre = (stname == "") and (namespace and (namespace=="ImGui" and "ig" or namespace.."_") or "ImPlot_") or stname.."_"
		return pre..funcname
	end
	parser.cname_overloads = cimgui_overloads
	parser:set_manuals(cimgui_manuals, modulename)
	parser.skipped = cimgui_skipped
	--parser.UDTs = {"ImVec2","ImVec4","ImColor","ImRect","ImPlotRect","ImPlotPoint","ImPlotLimits","ImPlotTime"}
	--parser.gentemplatetypedef = gentemplatetypedef
	parser.cimgui_inherited =  dofile([[../../cimgui/generator/output/structs_and_enums.lua]])
	--this list will expand all templated functions
	parser.ftemplate_list = {}
	parser.ftemplate_list.T = {"float", "double", "ImS8", "ImU8", "ImS16", "ImU16", "ImS32", "ImU32", "ImS64", "ImU64"}
	
	parser.custom_implementation = custom_implementation
	parser.custom_header = custom_header
	
	local defines = parser:take_lines(CPRE..header, names, COMPILER)
	--cpp2ffi.prtable("defines", defines)
	return parser
end
--generation
print("------------------generation with "..COMPILER.."------------------------")
local modulename = "cimplot"
local headers = [[#include "../implot/implot.h" 
]]
local headersT = {[[implot]]}
if INTERNAL_GENERATION then
    headers = headers .. [[#include "../implot/implot_internal.h"
	]]
	headersT[#headersT + 1] = [[implot_internal]]
end

save_data("headers.h",headers)
local include_cmd = COMPILER=="cl" and [[ /I ]] or [[ -I ]]
local extra_includes = include_cmd.." ../../cimgui/imgui "
local parser1 = parseImGuiHeader(extra_includes .. [[headers.h]],headersT,modulename)
os.remove("headers.h")
parser1:do_parse()

--cimgui_generation(parser1,modulename)
parser1:cimgui_generation( cimgui_header)
parser1:save_output()

print"all done!!"
